name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: cache - node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules/
          key: ${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: release
        id: release
        uses: google-github-actions/release-please-action@v3
        if: github.ref_name == 'add-automated-deploy'
        with:
          release-type: simple
          package-name: release-please-action
          default-branch: add-automated-deploy
          prerelease: true
          bootstrap-sha: fcc2e19069be3ee55c29e4ab19580d6e74965743 # exclude all commits prior to fork
      - name: store artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-artifact@v3
        with:
          name: artifact-package
          path: build/